// Per-industry demo datasets for the live interactive demo on each industry section.
// Numbers are illustrative and capability-based — never claimed as outcome guarantees.

import { Building2, Heart, Train, Zap, Building, GraduationCap } from 'lucide-react';

export const INDUSTRY_DEMOS = {
  government: {
    accent: 'from-indigo-600 to-blue-600',
    accentSolid: 'indigo',
    icon: Building2,
    headline: 'Plan a $2M renewal program against your council backlog — in 30 seconds.',
    sample: 'LGA Council · 1,432 assets',
    assets: [
      { name: 'Town Hall HVAC chiller', location: 'LGA Council Town Hall', condition: 4, risk: 86, crc: 184000, action: 'Replace within 6 months' },
      { name: 'Sports Centre roof', location: 'South West Sports Centre', condition: 4, risk: 78, crc: 420000, action: 'Re-deck — Q3 capital' },
      { name: 'Library AV system', location: 'Public Library', condition: 3, risk: 52, crc: 38000, action: 'Inspect Q2' },
      { name: 'Park irrigation pump', location: 'Hands Oval', condition: 5, risk: 92, crc: 12500, action: 'Emergency renewal' },
      { name: 'Carpark lighting LED', location: 'Civic Square', condition: 2, risk: 18, crc: 24000, action: 'Routine PM' },
    ],
    chart: [
      { year: '2026', backlog: 4.2, spent: 1.8 },
      { year: '2027', backlog: 3.6, spent: 2.0 },
      { year: '2028', backlog: 2.9, spent: 2.1 },
      { year: '2029', backlog: 2.1, spent: 2.0 },
      { year: '2030', backlog: 1.5, spent: 1.9 },
    ],
    workflow: ['Funding optimiser ranks renewals', 'Council pack auto-generated', 'Work orders dispatched', 'Savings logged in ledger'],
    kpi: { label: 'Capital plan optimised', value: '$2.0M', sub: 'risk-reduction-per-dollar maximised' },
    cta: { label: 'Open Funding Optimiser', href: '/FundingOptimiser' },
  },
  healthcare: {
    accent: 'from-rose-600 to-pink-600',
    accentSolid: 'rose',
    icon: Heart,
    headline: 'Stay audit-ready across every facility — compliance, sensors and lifecycle in one trail.',
    sample: 'Aged-care network · 12 facilities · 3,840 assets',
    assets: [
      { name: 'Backup generator G-2', location: 'Riverside Aged Care', condition: 3, risk: 71, crc: 96000, action: 'Compliance test due 14 days' },
      { name: 'Medical gas alarm panel', location: 'Hawthorn Hospital Wing', condition: 2, risk: 28, crc: 14000, action: 'Compliant — next audit Sep' },
      { name: 'Lift L-3 sheave', location: 'Eastside Clinic', condition: 4, risk: 82, crc: 110000, action: 'Replace before next inspection' },
      { name: 'HVAC chiller 4', location: 'Surgical Block', condition: 3, risk: 64, crc: 240000, action: 'Vibration trending up' },
      { name: 'Fire panel FP-1', location: 'Main Tower', condition: 2, risk: 22, crc: 8500, action: 'Compliant' },
    ],
    chart: [
      { year: 'Q1', backlog: 1.8, spent: 0.9 },
      { year: 'Q2', backlog: 1.6, spent: 1.0 },
      { year: 'Q3', backlog: 1.3, spent: 1.1 },
      { year: 'Q4', backlog: 0.9, spent: 1.2 },
    ],
    workflow: ['Sensor alert → condition update', 'Compliance trigger fires', 'Certified contractor dispatched', 'Audit-ready evidence pack stored'],
    kpi: { label: 'Compliance coverage', value: '100%', sub: 'every asset has an audit trail' },
    cta: { label: 'Open Compliance Center', href: '/Compliance' },
  },
  transport: {
    accent: 'from-emerald-600 to-teal-600',
    accentSolid: 'emerald',
    icon: Train,
    headline: 'See every switch, signal, bridge and crossing on one live network globe.',
    sample: 'Western rail line · 124 km · 2,180 assets',
    assets: [
      { name: 'Signal Box 12', location: 'Brunswick Junction', condition: 4, risk: 88, crc: 160000, action: 'Replace relay rack' },
      { name: 'Switch SW-31', location: 'Picton Loop', condition: 3, risk: 64, crc: 75000, action: 'Lubricate + monitor' },
      { name: 'Bridge BR-04 deck', location: 'Collie Crossing', condition: 4, risk: 79, crc: 1200000, action: 'Structural inspection Q2' },
      { name: 'Track segment W-8', location: 'Mile 47', condition: 3, risk: 55, crc: 89000, action: 'Geometry trending' },
      { name: 'Level crossing LC-9', location: 'Australind Rd', condition: 2, risk: 31, crc: 42000, action: 'Routine PM' },
    ],
    chart: [
      { year: 'Wk1', backlog: 12, spent: 6 },
      { year: 'Wk2', backlog: 14, spent: 8 },
      { year: 'Wk3', backlog: 10, spent: 9 },
      { year: 'Wk4', backlog: 7, spent: 9 },
    ],
    workflow: ['Network globe flags hotspot', 'Failure prediction runs', 'Maintenance window slot booked', 'Passenger-impact risk reduced'],
    kpi: { label: 'Network availability', value: '99.4%', sub: 'critical assets in green' },
    cta: { label: 'Open Network Globe', href: '/NetworkGlobe' },
  },
  utilities: {
    accent: 'from-amber-600 to-orange-600',
    accentSolid: 'amber',
    icon: Zap,
    headline: 'Predict failures across substations, pumps, turbines and pipelines — before they trip.',
    sample: 'Regional utility · 14 substations · 6,210 assets',
    assets: [
      { name: 'Transformer TX-6', location: 'Substation Alpha', condition: 4, risk: 84, crc: 1450000, action: 'Oil DGA flagged — schedule swap' },
      { name: 'Wind turbine WT-22', location: 'Coastal Farm', condition: 3, risk: 71, crc: 2800000, action: 'Gearbox vibration alert' },
      { name: 'Pump station P-5', location: 'River Intake', condition: 3, risk: 58, crc: 320000, action: 'Bearing change due' },
      { name: 'Pipeline segment 12B', location: 'Greenbushes', condition: 4, risk: 76, crc: 540000, action: 'Cathodic protection low' },
      { name: 'Solar inverter SI-9', location: 'Solar Farm 3', condition: 2, risk: 24, crc: 38000, action: 'Healthy' },
    ],
    chart: [
      { year: '24h', backlog: 8, spent: 2 },
      { year: '48h', backlog: 6, spent: 4 },
      { year: '72h', backlog: 4, spent: 5 },
      { year: '96h', backlog: 2, spent: 5 },
    ],
    workflow: ['Sensor stream → anomaly model', 'Failure probability rises', 'Outage-prevention WO created', 'Verified savings booked'],
    kpi: { label: 'Outage prevention value', value: '$1.42M', sub: 'projected this quarter' },
    cta: { label: 'Open Predictions', href: '/Predictions' },
  },
  property: {
    accent: 'from-violet-600 to-purple-600',
    accentSolid: 'violet',
    icon: Building,
    headline: 'Portfolio-wide depreciation, condition and capital plan — in one valuation view.',
    sample: 'REIT portfolio · 38 buildings · 18,400 assets',
    assets: [
      { name: 'Tower-A central plant', location: '500 Collins St', condition: 3, risk: 62, crc: 1850000, action: '7-year capex plan' },
      { name: 'Façade panel array', location: 'Riverside Mall', condition: 4, risk: 74, crc: 920000, action: 'Sealant renewal' },
      { name: 'Lift bank L1-L4', location: 'Northbank Tower', condition: 3, risk: 48, crc: 2400000, action: 'Modernisation Y3' },
      { name: 'Cooling tower CT-2', location: 'Tech Park 9', condition: 4, risk: 81, crc: 320000, action: 'Replace within 12 months' },
      { name: 'BMS controller', location: 'Civic Block', condition: 2, risk: 18, crc: 64000, action: 'Healthy' },
    ],
    chart: [
      { year: 'Y1', backlog: 8.4, spent: 3.2 },
      { year: 'Y2', backlog: 7.1, spent: 3.6 },
      { year: 'Y3', backlog: 5.8, spent: 4.0 },
      { year: 'Y4', backlog: 4.0, spent: 4.2 },
      { year: 'Y5', backlog: 2.6, spent: 4.0 },
    ],
    workflow: ['Portfolio valuation refresh', 'Cohort variance flags risk', 'Capital plan rebalanced', 'Investor pack exported'],
    kpi: { label: 'WDV vs CRC accuracy', value: '±2.1%', sub: 'audit-grade depreciation' },
    cta: { label: 'Open Valuation', href: '/Valuation' },
  },
  education: {
    accent: 'from-cyan-600 to-blue-600',
    accentSolid: 'cyan',
    icon: GraduationCap,
    headline: 'One register for every campus building, lab and grounds asset.',
    sample: 'University · 6 campuses · 11,200 assets',
    assets: [
      { name: 'Lecture theatre AV', location: 'Engineering Bldg', condition: 3, risk: 56, crc: 75000, action: 'Refresh before semester' },
      { name: 'Lab fume hood F-12', location: 'Chemistry Wing', condition: 4, risk: 81, crc: 28000, action: 'Annual cert overdue' },
      { name: 'Sports field irrigation', location: 'North Oval', condition: 3, risk: 49, crc: 92000, action: 'Summer maintenance' },
      { name: 'Library lift L-2', location: 'Main Library', condition: 2, risk: 24, crc: 240000, action: 'Compliant' },
      { name: 'Boiler B-3', location: 'Central Plant', condition: 4, risk: 77, crc: 410000, action: 'End-of-life — capex Y2' },
    ],
    chart: [
      { year: 'S1', backlog: 3.2, spent: 1.4 },
      { year: 'S2', backlog: 2.7, spent: 1.6 },
      { year: 'S3', backlog: 2.0, spent: 1.7 },
      { year: 'S4', backlog: 1.3, spent: 1.6 },
    ],
    workflow: ['Campus inspection round', 'Bulk condition update', 'Capital plan auto-rebuilt', 'Faculty briefing exported'],
    kpi: { label: 'Inspection coverage', value: '94%', sub: 'every campus on cycle' },
    cta: { label: 'Open Inspection Cycles', href: '/InspectionCycles' },
  },
};